# Generated by Django 3.0.7 on 2020-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('batting', models.CharField(choices=[('RCB', 'Royal Chalengers Bangalore'), ('KKR', 'Kolkata Knight Riders'), ('MI', 'Mumbai Indians'), ('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals')], max_length=10)),
                ('chasing', models.CharField(choices=[('RCB', 'Royal Chalengers Bangalore'), ('KKR', 'Kolkata Knight Riders'), ('MI', 'Mumbai Indians'), ('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals')], max_length=10)),
                ('venue', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('balls_left', models.IntegerField(default=0)),
                ('runs_l5', models.IntegerField(default=0)),
                ('wick_l5', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
    ]
