# Generated by Django 3.0.7 on 2020-07-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WinPredictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approvals',
            new_name='Approval',
        ),
    ]
